import SwiftUI
import AppFactoryKit
import AppFactoryKitRevenueCat

// ─────────────────────────────────────────────────────────────────────────
// OldPhotoRestoration — generated by AppFactoryKit appgen from niche "old-photo-restore".
// Per-app surface = this config + ContentView's feature. Everything that earns
// (onboarding, paywall, subscriptions, funnel) is inherited from the kit.
// ─────────────────────────────────────────────────────────────────────────

// Paste your RevenueCat public SDK key here to go live. Until then the app runs
// on a mock provider so you can preview the real paywall in the simulator.
private let revenueCatKey = "appl_REPLACE_ME"

@MainActor
enum OldPhotoRestorationFactory {
    static func make() -> AppFactory {
        let provider: PurchaseProvider = revenueCatKey == "appl_REPLACE_ME"
            ? MockPurchaseProvider()
            : RevenueCatPurchaseProvider(apiKey: revenueCatKey, entitlementID: "premium")

        let config = AppFactoryConfiguration(
            appName: "OldPhotoRestoration",
            purchaseProvider: provider,
            onboarding: OnboardingConfiguration(
                slides: [
                    .init(systemImage: "wand.and.stars",
                          title: "OldPhotoRestoration",
                          message: "Repair, deblur and colorize old/damaged photos."),
                    .init(systemImage: "photo.on.rectangle.angled",
                          title: "Go Pro",
                          message: "Unlimited restores, 4K export, batch.")
                ],
                presentsPaywallOnFinish: true,
                accent: .purple
            ),
            paywall: PaywallConfiguration(
                headline: "Unlock OldPhotoRestoration Pro",
                subheadline: "Unlimited restores, 4K export, batch.",
                benefits: [
                    .init(systemImage: "infinity", title: "Unlimited restores"),
                    .init(systemImage: "bolt.fill", title: "4K export"),
                    .init(systemImage: "nosign", title: "Batch")
                ],
                productIDs: ["old-photo-restore_yearly", "old-photo-restore_weekly"],
                highlightedProductID: "old-photo-restore_yearly",
                ctaTitle: "Continue",
                dismissButtonDelay: 4,
                isDismissable: true,
                termsURL: URL(string: "https://YOURDOMAIN.com/terms"),
                privacyURL: URL(string: "https://YOURDOMAIN.com/privacy"),
                style: PaywallStyle(accent: .purple, heroSystemImage: "wand.and.stars")
            )
        )
        return AppFactory(config)
    }
}

@main
struct OldPhotoRestorationApp: App {
    @StateObject private var factory = OldPhotoRestorationFactory.make()

    var body: some Scene {
        WindowGroup {
            ContentView()
                .appFactoryRoot(factory)
                .tint(.purple)
        }
    }
}
